name: 2024-uh
channels:
  - conda-forge
dependencies:
  - python
  - pip
  - jupyter
  - numpy
  - xarray
  - netcdf4
  - matplotlib
  - pyproj
  - pygmt
  # Fatiando packages
  - harmonica
  - verde
  - ensaio
  - boule
  # Notebook linting
  - nbqa
  - black
  - ruff
